module pdk.chart {

    requires java.desktop;
    requires org.jspecify;
    requires org.jfree.svg;
    requires com.orsonpdf.orsonpdf;

    exports pdk.chart;
    exports pdk.chart.annotations;
    exports pdk.chart.api;
    exports pdk.chart.axis;
    exports pdk.chart.block;
    exports pdk.chart.color;
    exports pdk.chart.date;
    exports pdk.chart.entity;
    exports pdk.chart.event;
    exports pdk.chart.imagemap;
    exports pdk.chart.labels;
    exports pdk.chart.legend;
    exports pdk.chart.plot.compass;
    exports pdk.chart.plot;
    exports pdk.chart.plot.dial;
    exports pdk.chart.plot.flow;
    exports pdk.chart.plot.pie;
    exports pdk.chart.renderer;
    exports pdk.chart.renderer.category;
    exports pdk.chart.renderer.xy;
    exports pdk.chart.swing;
    exports pdk.chart.swing.editor;
    exports pdk.chart.text;
    exports pdk.chart.text.format;
    exports pdk.chart.title;
    exports pdk.chart.urls;
    exports pdk.chart.util;
    exports pdk.chart.data;
    exports pdk.chart.data.category;
    exports pdk.chart.data.flow;
    exports pdk.chart.data.function;
    exports pdk.chart.data.gantt;
    exports pdk.chart.data.general;
    exports pdk.chart.data.io;
    exports pdk.chart.data.statistics;
    exports pdk.chart.data.time;
    exports pdk.chart.data.time.ohlc;
    exports pdk.chart.data.xml;
    exports pdk.chart.data.xy;
    exports pdk.chart.ms;
    exports pdk.chart.ms.label;
}